name: ublue latest

on:
  pull_request:
  merge_group:
  workflow_dispatch:
  schedule:
    - cron: "50 4 * * 1,2,3,4,5,6" # 4:50 UTC All But Sunday
    - cron: "50 4 * * 0" # 4:50 UTC Sunday

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: build
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        image_name:
          - base
          - kinoite
          - silverblue
          - cosmic-atomic
        image_variant:
          - main
          - nvidia
    with:
      image_name: ${{ matrix.image_name }}
      image_variant: ${{ matrix.image_variant }}
      image_version: latest
